ALTER TABLE proyecto ADD CONSTRAINT pk_proyecto PRIMARY KEY (id_proyecto);
ALTER TABLE evaluacion ADD CONSTRAINT pk_evaluacion PRIMARY KEY (id_evaluacion);
ALTER TABLE asignatura ADD CONSTRAINT pk_asignatura PRIMARY KEY (id_asignatura);
ALTER TABLE era ADD CONSTRAINT pk_era PRIMARY KEY (id_era);
ALTER TABLE curso ADD CONSTRAINT pk_curso PRIMARY KEY (id_curso);
ALTER TABLE programa_academico ADD CONSTRAINT pk_programa PRIMARY KEY (id_programa);
ALTER TABLE tipo_proyecto ADD CONSTRAINT pk_tipo_proyecto PRIMARY KEY (id_tipo_proyecto);
ALTER TABLE entregable ADD CONSTRAINT pk_entregable PRIMARY KEY (id_entregable);
ALTER TABLE tipo_entregable ADD CONSTRAINT pk_tipo_entregable PRIMARY KEY (id_tipo_entregable);
ALTER TABLE linea_de_investigacion ADD CONSTRAINT pk_linea PRIMARY KEY (id_linea);
ALTER TABLE profesor ADD CONSTRAINT pk_profesor PRIMARY KEY (id_profesor);
ALTER TABLE estudiante ADD CONSTRAINT pk_estudiante PRIMARY KEY (id_estudiante);
ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id_usuario);
ALTER TABLE rol ADD CONSTRAINT pk_rol PRIMARY KEY (id_rol);
ALTER TABLE permiso ADD CONSTRAINT pk_permiso PRIMARY KEY (id_permiso);
ALTER TABLE usuario_proyecto_rol ADD CONSTRAINT pk_usuario_proyecto_rol PRIMARY KEY (id_proyecto, id_usuario, id_rol);
ALTER TABLE curso_proyecto ADD CONSTRAINT pk_curso_proyecto PRIMARY KEY (id_curso, id_proyecto);
ALTER TABLE era_proyecto ADD CONSTRAINT pk_era_proyecto PRIMARY KEY (id_era, id_proyecto);
ALTER TABLE linea_investigacion_proyecto ADD CONSTRAINT pk_linea_investigacion_proyecto PRIMARY KEY (id_linea, id_proyecto);
ALTER TABLE ira ADD CONSTRAINT pk_ira PRIMARY KEY (id_ira);
ALTER TABLE ira_proyecto ADD CONSTRAINT pk_ira_proyecto PRIMARY KEY (id_ira, id_proyecto);
ALTER TABLE tipo_insumo ADD CONSTRAINT pk_tipo_insumo PRIMARY KEY (id_insumo);
ALTER TABLE prestamo_insumo ADD CONSTRAINT pk_prestamo_insumo PRIMARY KEY (id_prestamo);
ALTER TABLE universidad ADD CONSTRAINT pk_universidad PRIMARY KEY (id_universidad);
ALTER TABLE universidad_profesor ADD CONSTRAINT pk_universidad_profesor PRIMARY KEY (id_universidad, id_profesor);
ALTER TABLE universidad_estudiante ADD CONSTRAINT pk_universidad_estudiante PRIMARY KEY (id_universidad, id_estudiante);
ALTER TABLE universidad_programa_academico ADD CONSTRAINT pk_universidad_programa PRIMARY KEY (id_universidad, id_programa);
ALTER TABLE rep ADD CONSTRAINT pk_rep PRIMARY KEY (id_rep);
ALTER TABLE rep_proyecto ADD CONSTRAINT pk_rep_proyecto PRIMARY KEY (id_rep, id_proyecto);
ALTER TABLE invitado ADD CONSTRAINT pk_invitado PRIMARY KEY (id_invitado);
ALTER TABLE municipio ADD CONSTRAINT pk_municipio PRIMARY KEY (id_municipio);
ALTER TABLE region ADD CONSTRAINT pk_region PRIMARY KEY (id_region);
ALTER TABLE pais ADD CONSTRAINT pk_pais PRIMARY KEY (id_pais);
ALTER TABLE taller_transito ADD CONSTRAINT pk_taller_transito PRIMARY KEY (id_taller);
ALTER TABLE taller_proyecto ADD CONSTRAINT pk_taller_proyecto PRIMARY KEY (id_proyecto, id_taller);
