-- Agregar Primary Keys
ALTER TABLE proyecto ADD PRIMARY KEY (id_proyecto);
ALTER TABLE evaluacion ADD PRIMARY KEY (id_evaluacion);
ALTER TABLE asignatura ADD PRIMARY KEY (id_asignatura);
ALTER TABLE era ADD PRIMARY KEY (id_era);
ALTER TABLE curso ADD PRIMARY KEY (id_curso);
ALTER TABLE programa_academico ADD PRIMARY KEY (id_programa);
ALTER TABLE tipo_proyecto ADD PRIMARY KEY (id_tipo_proyecto);
ALTER TABLE entregable ADD PRIMARY KEY (id_entregable);
ALTER TABLE tipo_entregable ADD PRIMARY KEY (id_tipo_entregable);
ALTER TABLE linea_de_investigacion ADD PRIMARY KEY (id_linea);
ALTER TABLE profesor ADD PRIMARY KEY (id_profesor);
ALTER TABLE estudiante ADD PRIMARY KEY (id_estudiante);
ALTER TABLE usuario ADD PRIMARY KEY (id_usuario);
ALTER TABLE rol ADD PRIMARY KEY (id_rol);
ALTER TABLE permiso ADD PRIMARY KEY (id_permiso);
ALTER TABLE usuario_proyecto_rol ADD PRIMARY KEY (id_proyecto, id_usuario, id_rol);
ALTER TABLE curso_proyecto ADD PRIMARY KEY (id_curso, id_proyecto);
ALTER TABLE era_proyecto ADD PRIMARY KEY (id_era, id_proyecto);
ALTER TABLE linea_investigacion_proyecto ADD PRIMARY KEY (id_linea, id_proyecto);
ALTER TABLE ira ADD PRIMARY KEY (id_ira);
ALTER TABLE ira_proyecto ADD PRIMARY KEY (id_ira, id_proyecto);
ALTER TABLE tipo_insumo ADD PRIMARY KEY (id_insumo);
ALTER TABLE prestamo_insumo ADD PRIMARY KEY (id_prestamo);
ALTER TABLE universidad ADD PRIMARY KEY (id_universidad);
ALTER TABLE universidad_profesor ADD PRIMARY KEY (id_universidad, id_profesor);
ALTER TABLE universidad_estudiante ADD PRIMARY KEY (id_universidad, id_estudiante);
ALTER TABLE universidad_programa_academico ADD PRIMARY KEY (id_universidad, id_programa);
ALTER TABLE rep ADD PRIMARY KEY (id_rep);
ALTER TABLE rep_proyecto ADD PRIMARY KEY (id_rep, id_proyecto);
ALTER TABLE invitado ADD PRIMARY KEY (id_invitado);
ALTER TABLE municipio ADD PRIMARY KEY (id_municipio);
ALTER TABLE region ADD PRIMARY KEY (id_region);
ALTER TABLE pais ADD PRIMARY KEY (id_pais);
ALTER TABLE taller_transito ADD PRIMARY KEY (id_taller);
ALTER TABLE taller_proyecto ADD PRIMARY KEY (id_proyecto, id_taller);
