-- PRIMARY KEYS
ALTER TABLE proyecto ADD CONSTRAINT pk_proyecto PRIMARY KEY (id_proyecto);
ALTER TABLE evaluacion ADD CONSTRAINT pk_evaluacion PRIMARY KEY (id_evaluacion);
ALTER TABLE asignatura ADD CONSTRAINT pk_asignatura PRIMARY KEY (id_asignatura);
ALTER TABLE era ADD CONSTRAINT pk_era PRIMARY KEY (id_era);
ALTER TABLE curso ADD CONSTRAINT pk_curso PRIMARY KEY (id_curso);
ALTER TABLE programa_academico ADD CONSTRAINT pk_programa_academico PRIMARY KEY (id_programa);
ALTER TABLE tipo_proyecto ADD CONSTRAINT pk_tipo_proyecto PRIMARY KEY (id_tipo_proyecto);
ALTER TABLE entregable ADD CONSTRAINT pk_entregable PRIMARY KEY (id_entregable);
ALTER TABLE tipo_entregable ADD CONSTRAINT pk_tipo_entregable PRIMARY KEY (id_tipo_entregable);
ALTER TABLE linea_de_investigacion ADD CONSTRAINT pk_linea PRIMARY KEY (id_linea);
ALTER TABLE profesor ADD CONSTRAINT pk_profesor PRIMARY KEY (id_profesor);
ALTER TABLE estudiante ADD CONSTRAINT pk_estudiante PRIMARY KEY (id_estudiante);
ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id_usuario);
ALTER TABLE rol ADD CONSTRAINT pk_rol PRIMARY KEY (id_rol);
ALTER TABLE permiso ADD CONSTRAINT pk_permiso PRIMARY KEY (id_permiso);
ALTER TABLE ira ADD CONSTRAINT pk_ira PRIMARY KEY (id_ira);
ALTER TABLE prestamo_insumo ADD CONSTRAINT pk_prestamo_insumo PRIMARY KEY (id_prestamo);
ALTER TABLE universidad ADD CONSTRAINT pk_universidad PRIMARY KEY (id_universidad);
ALTER TABLE rep ADD CONSTRAINT pk_rep PRIMARY KEY (id_rep);
ALTER TABLE invitado ADD CONSTRAINT pk_invitado PRIMARY KEY (id_invitado);
ALTER TABLE municipio ADD CONSTRAINT pk_municipio PRIMARY KEY (id_municipio);
ALTER TABLE region ADD CONSTRAINT pk_region PRIMARY KEY (id_region);
ALTER TABLE pais ADD CONSTRAINT pk_pais PRIMARY KEY (id_pais);
ALTER TABLE taller_transito ADD CONSTRAINT pk_taller PRIMARY KEY (id_taller);

-- FOREIGN KEYS
ALTER TABLE proyecto ADD CONSTRAINT fk_proyecto_tipo FOREIGN KEY (id_tipo) REFERENCES tipo_proyecto(id_tipo_proyecto);
ALTER TABLE evaluacion ADD CONSTRAINT fk_eval_proyecto FOREIGN KEY (id_proyecto) REFERENCES proyecto(id_proyecto);
ALTER TABLE evaluacion ADD CONSTRAINT fk_eval_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario);
ALTER TABLE asignatura ADD CONSTRAINT fk_asignatura_programa FOREIGN KEY (id_programa) REFERENCES programa_academico(id_programa);
ALTER TABLE era ADD CONSTRAINT fk_era_asignatura FOREIGN KEY (id_asignatura) REFERENCES asignatura(id_asignatura);
ALTER TABLE curso ADD CONSTRAINT fk_curso_asignatura FOREIGN KEY (id_asignatura) REFERENCES asignatura(id_asignatura);
ALTER TABLE curso ADD CONSTRAINT fk_curso_profesor FOREIGN KEY (id_profesor) REFERENCES profesor(id_profesor);
ALTER TABLE entregable ADD CONSTRAINT fk_entregable_tipo FOREIGN KEY (id_tipo_entregable) REFERENCES tipo_entregable(id_tipo_entregable);
ALTER TABLE profesor ADD CONSTRAINT fk_profesor_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario);
ALTER TABLE estudiante ADD CONSTRAINT fk_estudiante_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario);
ALTER TABLE estudiante ADD CONSTRAINT fk_estudiante_programa FOREIGN KEY (id_programa) REFERENCES programa_academico(id_programa);
ALTER TABLE rol ADD CONSTRAINT fk_rol_permiso FOREIGN KEY (id_permiso) REFERENCES permiso(id_permiso);
ALTER TABLE usuario_proyecto_rol ADD CONSTRAINT fk_upr_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario);
ALTER TABLE usuario_proyecto_rol ADD CONSTRAINT fk_upr_rol FOREIGN KEY (id_rol) REFERENCES rol(id_rol);
ALTER TABLE usuario_proyecto_rol ADD CONSTRAINT fk_upr_proyecto FOREIGN KEY (id_proyecto) REFERENCES proyecto(id_proyecto);
ALTER TABLE curso_proyecto ADD CONSTRAINT fk_cp_curso FOREIGN KEY (id_curso) REFERENCES curso(id_curso);
ALTER TABLE curso_proyecto ADD CONSTRAINT fk_cp_proyecto FOREIGN KEY (id_proyecto) REFERENCES proyecto(id_proyecto);
ALTER TABLE era_proyecto ADD CONSTRAINT fk_ep_era FOREIGN KEY (id_era) REFERENCES era(id_era);
ALTER TABLE era_proyecto ADD CONSTRAINT fk_ep_proyecto FOREIGN KEY (id_proyecto) REFERENCES proyecto(id_proyecto);
ALTER TABLE linea_investigacion_proyecto ADD CONSTRAINT fk_lip_linea FOREIGN KEY (id_linea) REFERENCES linea_de_investigacion(id_linea);
ALTER TABLE linea_investigacion_proyecto ADD CONSTRAINT fk_lip_proyecto FOREIGN KEY (id_proyecto) REFERENCES proyecto(id_proyecto);
ALTER TABLE ira_proyecto ADD CONSTRAINT fk_ira_proy_ira FOREIGN KEY (id_ira) REFERENCES ira(id_ira);
ALTER TABLE ira_proyecto ADD CONSTRAINT fk_ira_proy_proy FOREIGN KEY (id_proyecto) REFERENCES proyecto(id_proyecto);
ALTER TABLE prestamo_insumo ADD CONSTRAINT fk_pinsumo_insumo FOREIGN KEY (id_insumo) REFERENCES tipo_insumo(id_insumo);
ALTER TABLE prestamo_insumo ADD CONSTRAINT fk_pinsumo_proyecto FOREIGN KEY (id_proyecto) REFERENCES proyecto(id_proyecto);
ALTER TABLE prestamo_insumo ADD CONSTRAINT fk_pinsumo_universidad FOREIGN KEY (id_universidad) REFERENCES universidad(id_universidad);
ALTER TABLE universidad_profesor ADD CONSTRAINT fk_uprof_u FOREIGN KEY (id_universidad) REFERENCES universidad(id_universidad);
ALTER TABLE universidad_profesor ADD CONSTRAINT fk_uprof_p FOREIGN KEY (id_profesor) REFERENCES profesor(id_profesor);
ALTER TABLE universidad_estudiante ADD CONSTRAINT fk_uest_u FOREIGN KEY (id_universidad) REFERENCES universidad(id_universidad);
ALTER TABLE universidad_estudiante ADD CONSTRAINT fk_uest_e FOREIGN KEY (id_estudiante) REFERENCES estudiante(id_estudiante);
ALTER TABLE universidad_programa_academico ADD CONSTRAINT fk_uprog_u FOREIGN KEY (id_universidad) REFERENCES universidad(id_universidad);
ALTER TABLE universidad_programa_academico ADD CONSTRAINT fk_uprog_p FOREIGN KEY (id_programa) REFERENCES programa_academico(id_programa);
ALTER TABLE rep_proyecto ADD CONSTRAINT fk_rp_rep FOREIGN KEY (id_rep) REFERENCES rep(id_rep);
ALTER TABLE rep_proyecto ADD CONSTRAINT fk_rp_proyecto FOREIGN KEY (id_proyecto) REFERENCES proyecto(id_proyecto);
ALTER TABLE invitado ADD CONSTRAINT fk_invitado_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario);
ALTER TABLE municipio ADD CONSTRAINT fk_mun_region FOREIGN KEY (id_region) REFERENCES region(id_region);
ALTER TABLE region ADD CONSTRAINT fk_region_pais FOREIGN KEY (id_pais) REFERENCES pais(id_pais);
ALTER TABLE taller_proyecto ADD CONSTRAINT fk_tp_proy FOREIGN KEY (id_proyecto) REFERENCES proyecto(id_proyecto);
ALTER TABLE taller_proyecto ADD CONSTRAINT fk_tp_taller FOREIGN KEY (id_taller) REFERENCES taller_transito(id_taller);
